### ISSUE TITLE
[FEATURE] Dify - support changing STORAGE_TYPE env value

### ISSUE THREAD

**Issue by deoomen** [douban/charts#88]
**Describe the bug**

In Dify helmchart there is no option to change hardcoded `s3` value of env `STORAGE_TYPE`. And there is no option to use anything else than S3 storage. Env is hardcoded in _helpers.tpl

**To Reproduce**

?

**Expected behavior**

Option to use other storages than S3.

**Screenshots**

**Additional context**

**Comment by LeoQuote** [comment]
PR are welcomed, I think it’s a feature not a bug

**Comment by LeoQuote** [comment]
I think using s3 would bring the user more convenience since it would not require a shared directory.

Shared directory between pods can lead to many problems like write conflict, please consult to this SO answer if you want to know more: https://stackoverflow.com/a/36524584

Apart from the potential issue brought by shared directory, you have to define volume mount for each component of dify.

I would recommend not to implement it, but like I said before, PRs are always welcomed as long as it brings no breaking change.

**Comment by deoomen** [comment]
Thanks for answer. I want to use Google Cloud Storage instead s3. But maybe someone else will want use something else. Dify allow usage of different storage methods and IMHO your helm chart is the best from these that I have found. Later I'll try to do some PR.

**Comment by LeoQuote** [comment]
Thanks for your clarification, now I totally understand you, it should be very simple to achieve your goal, just change the code here 

https://github.com/douban/charts/blob/164332b343625649e8cdae44505b0fa65174ffcd/charts/dify/templates/_helpers.tpl#L107 and set default value of `global.stroageType` to `s3` and everything would be ok.

More documents in readme are also welcomed.
